[package]
edition = "2021"
name = "rwalk"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.1"
[dependencies.sdl2]
git = "https://github.com/rust-sdl2/rust-sdl2"
